Add input conflict check to build tweaks workflow
Added a step to check for conflicting inputs in the build workflow.

diff --git a/.github/workflows/_build_tweaks.yml b/.github/workflows/_build_tweaks.yml
--- a/.github/workflows/_build_tweaks.yml
+++ b/.github/workflows/_build_tweaks.yml
@@ -89,6 +89,13 @@ jobs:
     runs-on: macos-latest
 
     steps:
+      - name: Check for conflicting inputs
+        run: |
+          if [[ "${{ inputs.enable_ytpf }}" == "true" && "${{ inputs.enable_ytpfBETA }}" == "true" ]]; then
+            echo "::error::You can't select both inputs 'Integrate YTPlaybackFix' and 'Integrate YTPlaybackFix beta' at the same time. Please select only one of them."
+            exit 1
+          fi
+          
       - name: Install Dependencies
         run: brew install make ldid dpkg
 
